#=================================[=]
title: "My Notes"
lang: "id"

#=================================[=]
keywords: ""

#=================================[=]
owner: "Putra Jaya"
description: "Tempat Berbagi Keluh Kesah"
google_analytics: "G-W9TMTZZYG5"
timezone: Asia/Jakarta

#=================================[=] 
url: ""
baseurl: ""

#=================================[=]
github: "https://github.com/masputrawae/"
twitter: "https://x.com/Masputrawae"
facebook: "https://www.facebook.com/profile.php?id=61566134978045"
instagram: "https://www.instagram.com/masputrawae/"
discord: "https://discord.gg/nM4EP8DJFZ"
email: "masputrawae.official@gmail.com"
youtube: "https://www.youtube.com/@masputrawae"

#=================================[=]
paginate: 5
paginate_path: "/page:num/"
excerpt_separator: ""

#=================================[=]
collections:
  pages:
    output: true
  tabs:
    output: true
    sort_by: order
  categories:
    output: true
    sort_by: order
    
#=================================[=]
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:title/"      
      
#=================================[=]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap
  
#=================================[=]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - drafts
  - .sass-cache/
  - .jekyll-cache/

#=================================[=]
markdown: kramdown
